---
- name:  Windows Update Download Only
  hosts: all
  gather_facts: yes
  tasks:
    - name: Download Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
        state: downloaded
        reboot: no
        log_path: C:\Ansible\download_log.txt
